apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-races
  labels:
    app: races
spec:
  replicas: 1
  selector:
    matchLabels:
      app: races
  template:
    metadata:
      labels:
        app: races
    spec:
      containers:
      - name: app
        image: rpg-races:dev
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: pg-races
        - configMapRef:
            name: dnd-client
      - name: pg
        image: postgres:14-alpine
        envFrom:
        - secretRef:
            name: pg-races
