apiVersion: v1
kind: Secret
metadata:
  name: pg-races
type: Opaque
# NOTE This is a DEMO and NOT good security
stringData:
  POSTGRES_HOST: localhost
  POSTGRES_PORT: "5432"
  POSTGRES_USER: dev
  POSTGRES_PASSWORD: dev
  POSTGRES_DB: races